app:
    image: debian:jessie
    volumes:
        - .:/var/www/app
        - ./logs/cakephp:/var/www/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    volumes:
        - ./logs/mysql:/var/log/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cakephp
        MYSQL_USER: root
        MYSQL_PASSWORD: root
# If you prefer Postgres
#db:
#    image: postgres
#    ports:
#        - 5432:5432
#    environment:
#        POSTGRES_USER: root
#        POSTGRES_PASSWORD: root
#        POSTGRES_DB: cakephp
php:
    image: cake17/cakephp:php56-fpm
    expose:
        - 9000:9000
    volumes_from:
        - app
    links:
        - db
    working_dir: /var/www/app
nginx:
    image: cake17/cakephp:nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - ./logs/nginx:/var/log/nginx
