application:
    #image: cake17/code
    build: .
    volumes:
        - .:/var/www/app
        - logs:/var/www/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cakephp
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    #image: cake17/php-fpm
    build: ../php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    #image: cake17/nginx
    build: ../nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - logs/nginx:/var/log/nginx
